package view;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;

public class GamePage {

    @FXML
    private Button buttonF1T1;
    private Button buttonF1T2;
    private Button buttonF1T3;
    private Button buttonF1T4;
    private Button buttonF2T1;
    private Button buttonF2T2;
    private Button buttonF2T3;
    private Button buttonF2T4;
    private Button buttonF3T1;
    private Button buttonF3T2;
    private Button buttonF3T3;
    private Button buttonF3T4;
    private Button buttonF4T1;
    private Button buttonF4T2;
    private Button buttonF4T3;
    private Button buttonF4T4;
    private Button buttonF5T1;
    private Button buttonF5T2;
    private Button buttonF5T3;
    private Button buttonF5T4;
    private Button buttonF6T1;
    private Button buttonF6T2;
    private Button buttonF6T3;
    private Button buttonF6T4;
    private Button buttonF7T1;
    private Button buttonF7T2;
    private Button buttonF7T3;
    private Button buttonF7T4;
    private Button buttonF8T1;
    private Button buttonF8T2;
    private Button buttonF8T3;
    private Button buttonF8T4;
    private Button buttonF9T1;
    private Button buttonF9T2;
    private Button buttonF9T3;
    private Button buttonF9T4;
    private GridPane factory1;
    private GridPane factory2;
    private GridPane factory3;
    private GridPane factory4;
    private GridPane factory5;
    private GridPane factory6;
    private GridPane factory7;
    private GridPane factory8;
    private GridPane factory9;
    private VBox middle;
    private HBox player1Floor;
    private Label player1Name;
    private GridPane player1PL1;
    private GridPane player1PL2;
    private GridPane player1PL3;
    private GridPane player1PL4;
    private GridPane player1PL5;
    private Label player1Score;
    private GridPane player1W1;
    private GridPane player1W2;
    private GridPane player1W3;
    private GridPane player1W4;
    private GridPane player1W5;
    private HBox player2Floor;
    private Label player2Name;
    private GridPane player2PL1;
    private GridPane player2PL2;
    private GridPane player2PL3;
    private GridPane player2PL4;
    private GridPane player2PL5;
    private Label player2Score;
    private GridPane player2W1;
    private GridPane player2W2;
    private GridPane player2W3;
    private GridPane player2W4;
    private GridPane player2W5;
    private HBox player3Floor;
    private Label player3Name;
    private GridPane player3PL1;
    private GridPane player3PL2;
    private GridPane player3PL3;
    private GridPane player3PL4;
    private GridPane player3PL5;
    private Label player3Score;
    private GridPane player3W1;
    private GridPane player3W2;
    private GridPane player3W3;
    private GridPane player3W4;
    private GridPane player3W5;
    private HBox player4Floor;
    private Label player4Name;
    private GridPane player4PL1;
    private GridPane player4PL2;
    private GridPane player4PL3;
    private GridPane player4PL4;
    private GridPane player4PL5;
    private Label player4Score;
    private GridPane player4W1;
    private GridPane player4W2;
    private GridPane player4W3;
    private GridPane player4W4;
    private GridPane player4W5;
    private VBox playerboard1;
    private VBox playerboard2;
    private VBox playerboard3;
    private VBox playerboard4;
}
